### ISSUE TITLE
IE9 - firebug lite pops up automatically

### ISSUE THREAD

**Issue by tom-daly** [patik/console.log-wrapper#32]
Experiencing an issue in IE9, where firebuglite automatically opens everytime.

I've discovered this ever while opening the IE f12 developer tools

Function.prototype.bind: 'this' is not a Function object
Line 7, character 13

![image](https://cloud.githubusercontent.com/assets/9259305/6289232/99555c56-b8ec-11e4-8096-c13f984c6d1a.png)

end users reported this, and I was able to reproduce and simulate using browserstack Win7/Ie9

![image](https://cloud.githubusercontent.com/assets/9259305/6289489/80cf0626-b8ee-11e4-95cc-01de417341dd.png)

**Comment by patik** [comment]
Are you running any other third-party scripts (such as Modernizr)?

**Comment by tom-daly** [comment]
yes - I have quite a few loading

![image](https://cloud.githubusercontent.com/assets/9259305/6315503/10b7a28c-b9d2-11e4-8f82-b073ec788f7e.png)

**Comment by patik** [comment]
I found the problem resulting in the error `Function.prototype.bind: 'this' is not a Function object` and I believe I have a fix. Please try this version: https://github.com/patik/console.log-wrapper/blob/ie9-function-prototype-bind/consolelog.js

I could not reproduce the issue of Firebug appearing in IE9, but I have a hunch the above fix will address it.

**Comment by tom-daly** [comment]
Thanks for the fast response! Looks promising.

No script errors are thrown when viewing in IE9 dev bar.
![image](https://cloud.githubusercontent.com/assets/9259305/6319386/92aee3b6-ba88-11e4-9607-af324a491123.png)

I saw the firebug pop up the first few times - might be caching w/ browserstack. I'll continue testing it this week and let you know either way.

**Comment by patik** [comment]
Firebug Lite should never appear for IE9 — it's only meant for IE7 and other browsers with no console at all. I wonder if another script is causing it to appear. Perhaps you could try commenting out line 64 in consolelog.js (which injects the FB script) and see if it still happens.

**Comment by tom-daly** [comment]
FB Lite is included on IE in all versions when using browserstack. commenting out line 64 prevents the popup.

the last parameter in that line loads firebug with options,  '#startOpened',  this means start opened = true, I set that to false but still getting popup. I'm good with commenting out FB lite. we won't need it in IE as long as the errors are gone.
